### ISSUE TITLE
RangeError (index) : Invalid value: Valid value range is empty: 0

### ISSUE THREAD

**Issue by hanimhanna** [vcjpierre/flutter-scores-app#2]
hi, after runing the app i get this error on the screen 

RangeError (index) : Invalid value: Valid value range is empty: 0

any solution ?

**Comment by vcjpierre** [comment]
Hi, u need put your api key in lib/services/soccer.dart file. 

To get the api key, you need to subscribe to the API-FOOTBALL. https://rapidapi.com/api-sports/api/api-football/
Then get your Application Key in the Developer Dashboard from RapidAPI. https://rapidapi.com/developer/apps

**Comment by hanimhanna** [comment]
thanks! but how much Approximately it costs per month to run it ?!

**Comment by hanimhanna** [comment]
i subscribed and replaced the api key but still when runing the app getting red screen (RangeError(index......)

x-special/nautilus-clipboard
copy
file:///home/user/Pictures/Screenshot%20from%202021-02-05%2020-31-08.png

**Comment by hanimhanna** [comment]
@vcjpierre can you inform me please ! is there return statement i have to put it below the var body; ?

**Comment by hanimhanna** [comment]
i think this is the reason for error but what could i replace zero with what ?! 

Widget pageBody (List<SoccerMatch> allmatches) {
  return Column(
    children: [
      Expanded(
        flex: 2,
        child: Container(
          child: Padding(
            padding: EdgeInsets.symmetric(horizontal: 18.0, vertical: 24.0),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              crossAxisAlignment: CrossAxisAlignment.center,
              children: [
                teamStat("Local Team", allmatches[0].home.logoUrl,
                  allmatches[0].home.name),
                goalStat(allmatches[0].fixture.status.elapsedTime,
                  allmatches[0].goal.home, allmatches[0].goal.away),
                teamStat("Visitor Team", allmatches[0].away.logoUrl,
                  allmatches[0].away.name),
              ],
            ),
          ),
        ),
      ),

**Comment by vcjpierre** [comment]
Sorry my fault. This is the correct website to get the API Key: https://dashboard.api-football.com/

I will update the README with more information. Greetings.

**Comment by hanimhanna** [comment]
ok thanks! but may you tell me in details how to get the API from that web please ?!appriciate you :) ..

**Comment by vcjpierre** [comment]
@hanimhanna You need sign up and then go https://dashboard.api-football.com/profile?access

**Comment by hanimhanna** [comment]
thanks alot!appriciated :)

**Comment by hanimhanna** [comment]
hello ! is there any way to add more than this legue (ex: liga,...) ??
please inform me and thank you : )

**Comment by vcjpierre** [comment]
@hanimhanna I'm not sure. But you can do another view and show the league results using LaLiga Id: https://v3.football.api-sports.io/fixtures?season=2020&league=39 

You can see the documentation for more examples: https://api-sports.io/documentation/football/v3#operation/get-fixtures
