### ISSUE TITLE
on playstore when i click to open .. nothing shows on , app not available !

### ISSUE THREAD

**Issue by hanimhanna** [vcjpierre/flutter-scores-app#3]
hi, after releasing the apk for the app on play store when i click to open it no screen shows on .. a bug maybe or error , but when i test it on the vscode it opened and every thing is good ! , please may you feed me back for a solution ! thank you

**Comment by vcjpierre** [comment]
Hi @hanimhanna make sure you have internet permissions added in src -> main -> AndroidManifest.xml.

`<uses-permission android:name="android.permission.INTERNET" />`

**Comment by hanimhanna** [comment]
problem solved ! thank you sir ..
